# Generated by Django 4.1 on 2022-09-08 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_superskill_alter_skill_superskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superskill',
            name='level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
