# Generated by Django 4.1 on 2022-09-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_superskill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=256)),
                ('school', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
