# Generated by Django 4.1 on 2022-09-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_year_end_education_year_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='period',
        ),
    ]
