# Generated by Django 4.1 on 2022-09-14 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_education_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_start',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1992), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
