# Generated by Django 4.1 on 2022-09-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_education_year_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_start',
        ),
    ]
