# Generated by Django 4.1 on 2022-09-14 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_education_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year_end',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1992), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AddField(
            model_name='education',
            name='year_start',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1992), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
