# Generated by Django 4.1 on 2022-09-14 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_education_year_end_education_year_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1992), django.core.validators.MaxValueValidator(2022)])),
                ('year_end', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1992), django.core.validators.MaxValueValidator(2022)])),
                ('title', models.CharField(max_length=128)),
                ('work_place', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
